services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: docmanager
      POSTGRES_USER: docmanager
      POSTGRES_PASSWORD: YkhsD4DFgJ04xTXtAJ5Wc4QZ30IlwPeE

  minio:
    image: minio/minio:latest   # RIP. latest minio build, actually RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 7EoSor9oBHYH59Qq5D6FkDn9ACou2O5s
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

  init:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    command: >
      sh -c "
      echo 'Waiting for database...' &&
      until pg_isready -h db -U docmanager; do sleep 2; done &&
      python -u /init_data.py &&
      python -u /init_minio.py &&
      tail -f /dev/null
      "
    environment:
      DB_NAME: docmanager
      DB_USER: docmanager
      DB_PASSWORD: YkhsD4DFgJ04xTXtAJ5Wc4QZ30IlwPeE
      DB_HOST: db
      DB_PORT: 5432
      MINIO_ENDPOINT: "minio:9000"
      MINIO_SECURE: "False"
      MINIO_BUCKET: documents

  web:
    build: ./docmanager
    command: >
      sh -c "
      echo 'Waiting for database...' &&
      until pg_isready -h db -U docmanager; do sleep 2; done &&
      python manage.py migrate --run-syncdb &&
      gunicorn docmanager.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    environment:
      DEBUG: "False"
      DJANGO_SECRET_KEY: "qZHkK1nQeiDdotWWBL9GTCVlY75X9d6e"
      DB_NAME: docmanager
      DB_USER: docmanager
      DB_PASSWORD: YkhsD4DFgJ04xTXtAJ5Wc4QZ30IlwPeE
      DB_HOST: db
      DB_PORT: 5432
      MINIO_ENDPOINT: "minio:9000"
      MINIO_SECURE: "False"
      MINIO_BUCKET: documents
      JWT_SECRET_KEY: iM3CNKOS6dPTEo0P3KSmdKOeV4rDeQDS
    ports:
      - "8000:8000"

